<?php

use Drupal\node\Entity\Node;
use Drupal\Core\Url;


/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function myadmin_preprocess_page(&$variables) {
  // Charger les 5 derniers articles publiés
  // $nids = \Drupal::entityQuery('node')
  //   ->condition('type', 'cart')
  //   ->range(0, 5)
  //   ->sort('created', 'DESC')
  //   ->execute();

  // $nodes = Node::loadMultiple($nids);
  // $articles = [];
  // foreach ($nodes as $node) {
  //   $articles[] = [
  //     'id' => $node->id(),
  //     'title' => $node->getTitle(),
  //     'created' => \Drupal::service('date.formatter')->format($node->getCreatedTime(), 'short'),
  //   ];
  // }
  // // Injecter dans drupalSettings
  // $variables['#attached']['drupalSettings']['vueArticles'] = $articles;
  $current_user = \Drupal::currentUser();
  $data = [
    'isLoggedIn' => $current_user->isAuthenticated(), // TRUE ou FALSE
    'uid' => $current_user->id(),
    'username' => $current_user->getAccountName(),
    'baseUrl' => Url::fromRoute('<front>', [], ['absolute' => TRUE])->toString(),
    'menu' => [
      [ "id" => 1, "name" => "Caisse", "path" => "/", "icon" => "fas fa-home" ],
      [ "name" => "Commandes", "path" => "/orders", "icon" => "fas fa-shopping-cart"],
      [ "name" => "Clients", "path" => "/clients", "icon" => "fas fa-users"],
    ]
  ];

  $variables['#attached']['drupalSettings']['data'] = $data;
}